### ISSUE TITLE
Add a delete button

### ISSUE THREAD

**Issue by missEldgard** [Nenotriple/img-txt_viewer#13]
It would be great to have a delete button to delete a specific image if we notice it is too blurred to be kept, for example.

**Comment by Nenotriple** [comment]
I've added this function to the ui as a menubar action as of v1.7
You can find it in Options > Delete_Pair

A warning popup will confirm the choice or give you an option to cancel.
This does not send the image to the recycle bin, deleting the image is permanent.

Thank you so much for using the app 👍
