### ISSUE TITLE
[feature request]: Filter out a subset of images based on the text file, and text highlight

### ISSUE THREAD

**Issue by TeKett** [Nenotriple/img-txt_viewer#18]
Id like to start with saying this tool is great and makes it very easy to caption images. Thank you.

When working with very large image sets, its quite inconvenient to go through and check the text for every image to see if a word/token/tag/phrase exists.

For QoL it would be very useful if we could filter out a subset of images based on if a string exist or doesn't exist. I know there are other ways i could do this, like using batch/regedit via the terminal and move all the images to its own folder, or using notepad++ search and load up each text file individually, but it would be way more convenient if it could be done in the program directly.

Another thing that would improve QoL is if the text highlight could highlight any string, and not just duplicated tags. So you can have it highlight one or more tags at all times. Not having to scan through the entire caption to find what you are looking for would make it so you could blast through the images much quicker.

**Comment by Nenotriple** [comment]
Thank you so much, I'm glad it's helpful!

I've incorporated both of your suggestions in [v1.85](https://github.com/Nenotriple/img-txt_viewer/releases/tag/v1.85). You can find these tools in the bottom toolbar under: `Filter Pairs` and `Active Highlights`. A nice trickle down feature is that other text tools (S&R/Prefix/Append) will respect the filtered pairs. This could be really handy to help those tools be useful in more scenarios.

Let me know if it's somehow not what you were expecting, or if you encounter any issues.
