### ISSUE TITLE
Feature request - Dataset Overview Mode

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nenotriple/img-txt_viewer#20]
A way to view the folder dataset in some kind of overview mode.

For example, by grouping images into image size buckets or formats, to easily be able to do a batch operation on a group.

Like, let's say crop or expand all images in bad resolutions, or resize images of one to another nearby resolution.

Or a way to group by extension, and then convert all JPGs and JPEGs to PNGs (with warnings for if there's name overlap). And it also renames the .txt pairs at the same time.

These are all things that I do manually occasionally, or with small scripts, but would be great in a tool like this.
But it may also take away from the simplicity of the project, so it may not be suitable.

**Comment by Nenotriple** [comment]
This sounds reasonable, but I'll have to think about it for awhile to determine the best way to implement an overview and how to tie it together with the existing tools. I could see how it would be useful, so I don't want to flat out say no, but it will be tricky to get it all working.

Could you give some examples of what you consider a "bad resolution" and a use case for resizing to another nearby resolution? I assume you mean anything not square or a standard aspect ratio?

> Or a way to group by extension, and then convert all JPGs and JPEGs to PNGs (with warnings for if there's name overlap). And it also renames the .txt pairs at the same time.

The next release will have a batch rename and convert tool that will do this. But it currently always outputs JPG, and you can't pick and choose what to convert, it just acts on the entire folder. I could make it output PNG, but the file size and output speed per image were much worse, and outputting a 100% quality JPG is visibly indistinguishable from the original.

<br>

I don't see this happening for the next release, but it would be something to focus on after that!

**Comment by MNeMoNiCuZ** [comment]
Apologies for the slow reply.

What I meant by bad resolution was some built-in tool where you enter resolutions for your buckets. Let's say you want to have 1024x1024, 768x1024, and 1024x768, and you only want those resolutions.

It could then mark which images aren't that, or aren't near that. And perhaps auto-crop images that are near that?
Basically, trying to automate or at least include functionality that you would currently use https://www.birme.net/ for.

This is nothing important, it can all be done there. Just brainstorming additional functionality. Probably not worth the effort unless it sounds like a fun thing for you.

I think all 100% quality JPG is fine. It's good if it ensures it's all the same format.

**Comment by Nenotriple** [comment]
No problem it's totally fine.

I think I understand better now after messing with birme, I'll definitely keep this in mind.

**Comment by MNeMoNiCuZ** [comment]
Sounds good!

It's a good thing to not have too many resolution sizes. The more they can remain exactly the same, the better. It may be ratio-based, or resolution-based, not entirely sure. But the models tend to perform better if you limit the number of size buckets it has to train on. I usually go with one square, one horizontal, and one vertical.

**Comment by Nenotriple** [comment]
So I've had some time to attempt this and I didn't really get far on an overview :)

I do like the idea of trying to make the image "buckets" beforehand so you have a better sense of what's going into the model, but it's somewhat tricky to make it all work cleanly.

When I got frustrated on that stuff I made a new tool for batch cropping images. This works similarly to birme, but without smartcrop.js the results are lackluster (center crop).

Have you tried out the Batch Resize Images tool? It may be able to achieve something like what you're looking for. For example you can set it to: `Resize=Longer Side, Condition=Upscale and Downscale, Size=1024`, and all images will be resized so their longest side is exactly 1024 while maintaining aspect ratio.

I generally do something like that and let the kohya_ss bucketing system work things out normally. It's not the same as your idea of ensuring just a few aspect ratios/resolutions but I think it's close.

I'm going to close this for now because I don't intend to work on it much more, but it's still a possibility. Sorry I couldn't come up with something more for you!

**Comment by MNeMoNiCuZ** [comment]
Too bad it didn't work out.
It's no problem to keep using Birme honestly. I was just thinking of matching features.

Thanks for giving it a go.

I think you are right in that some kind of focus-detection would be the best for a tool like this. That's a model of it's own :)

**Comment by Nenotriple** [comment]
It took a while, but I've just implemented an overview (referred to as 'Image Grid' in the app) for v1.92. [#012c023](https://github.com/Nenotriple/img-txt_viewer/blob/main/main/scripts/image_grid.py)

You can currently use it to view all images, filter images with or without a text pair, and quickly navigate to an image.

Thank you for the suggestion. This is something I've wanted to do for a long time, and it's easy to keep putting stuff like this off for later

**Comment by MNeMoNiCuZ** [comment]
Nice! That works really well!
My only recommendation is that the "Auto close"-option is off by default.
I don't think having it as true makes the most sense as a default behavior.
It's a bit annoying that this option is not saved, and it keeps defaulting to true.

Additionally, it would be nice to be able to maximize and resize the image grid. Aside from technical difficulties with implementation, I don't see a good reason to keep it this small and limited.

Additionally, it should probably be implemented as a proper window, instead of whatever it is now.

As it is, if I open something over it, like my web browser to type out these words, and then go back to the program, the Image Grid window does not show up. It's permanently hidden behind my web browser or other application overlapping it.
