### ISSUE TITLE
[Bug] Removes/empties the first caption file

### ISSUE THREAD

**Issue by younyokel** [Nenotriple/img-txt_viewer#23]
Have noticed this problem for a while but always thought it was my mistake.

Auto-save should be enabled from the launch.

1. Exit the app in any folder
2. Re-open the app for it to ask to reload last directory, click “No”
3. Press "Browse" and navigate to the folder with the pre-made caption files
4. First opened caption is empty and in the directory, the first caption file is nowhere to be found

**Comment by Nenotriple** [comment]
Thank you for reporting this issue. I was able to reproduce it. It looks like auto-save was triggering before the text box was filled. Because saving an empty text file will actually delete it, this was causing the text pair to appear empty and be deleted.

This was a simple fix. I just check if the text box widget exists, if it doesn't exist, then auto-save is temporarily disabled.

Give me about a day or two and I'll have a full release ready.

**Comment by TeKett** [comment]
The fix causes a similar issue. When you swap to another folder the text currently in the textbox replaces the text of the loaded text file, overwriting it.

**Comment by Nenotriple** [comment]
I'm assuming you're manually entering a path in the directory entry and pressing `Enter` to set the path. I can't reproduce the issue any other way. If so, this appears to be unrelated to this issue/fix, I checked, and the issue still happens in older versions. But that doesn't really matter, and it is a very similar issue.


There was *probably* a good reason at the time, but I just noticed that I'm not resetting the image index when using `set_working_directory`.  This basically means the text box and image index are never reset, but only when using the `Enter` key to set the directory, not when using the `Browse` button.

I'll have a hotfix for the current release later today, thank you!

**Comment by TeKett** [comment]
No, i do browse, go to another directory, and then select folder. The problem is the auto save, so its the same issue it seems.

**Comment by Nenotriple** [comment]
My mistake, I must have double clicked the autosave checkbutton or something. I'm not sure I was actually testing with autosave enabled. I'm fairly sure that I've tracked the issue down. 

Please try this version [v1.93.2_lite](https://github.com/Nenotriple/img-txt_viewer/releases/download/v1.93.1/v1.93.2_img-txt_viewer_lite_BETA.exe) and let me know if it works for you.

**Comment by Tone91999** [comment]
Do you think u could help me fix my python image editor? Im trying to make it so that it snaps to the center line when dragging close to middle but I think the different aspect ratios of images are messing it up https://paste.pythondiscord.com/7FTA

**Comment by Nenotriple** [comment]
> Do you think u could help me fix my python image editor?

I really don't have the time at the moment, sorry.
