### ISSUE TITLE
Improve word double-click selection

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nenotriple/img-txt_viewer#26]
![image](https://github.com/user-attachments/assets/be0f07f5-7f7a-432a-aa30-ac3e454ee23f)

If I double-click the word on the left side here, I expect to only select that word.
If I double-click the word on the right side, I expect to select only that word, and not the comma.

As it is, I get the entire word, including pipe (|) and comma.

**Comment by Nenotriple** [comment]
This issue is fixed in v1.95 952ee74

- Improved text selection logic for the primary text box and most text entries, treating common punctuation and symbols as word boundaries on double-click and allowing you to select entire entry text strings with a triple-click.
