### ISSUE TITLE
Modified annotations & \n characters being stripped in the annotation box

### ISSUE THREAD

**Issue by abdullahmeda** [Nenotriple/img-txt_viewer#28]
Text displayed in the UI is modified as well stripped of the \n characters. In the following example in the case of modified text, note the difference at the start of the text itself. It'd be awesome if this could be fixed. Thanks :)

The UI:
![ui](https://github.com/user-attachments/assets/a4891582-fe11-416a-8163-7d94fe911f03)

The Ground truth which is how it should appear in the UI:
![ground truth](https://github.com/user-attachments/assets/566371bb-0107-4c6e-b346-84e452dcc760)

**Comment by Nenotriple** [comment]
Please try disabling the option `Cleaning Text on Save`, and try again. This should allow you so save text in that format.

Top menu bar > Options > Cleaning Text on Save
You can also toggle the setting from the text box right-click menu.

The text cleaning function was designed to accommodate captions separated by commas like: `tag1, tag2, another tag, ...` etc.

**Comment by abdullahmeda** [comment]
That did work. Thanks!

**Comment by Nenotriple** [comment]
Thanks for letting me know, I'm glad it worked.
