### ISSUE TITLE
Bug: Text-image pairs are becoming scrambled.

### ISSUE THREAD

**Issue by UrzasLegacy** [Nenotriple/img-txt_viewer#31]
`  - Sometimes when using `delete pair`, the contents of the text box seem to automatically get saved to that index. For example: I delete index 4 and now index 5 has the text saved to it instead.`

I'm not 100% sure if this is what happened with me, but I noticed at some point that some of my text image pairs were swapped. Very painful bug to rectify!

I love your app, so I wanted to see if I could bang this one out. I noticed in your Todo section you are already aware of the issue :P Have you made any headway? 

Edit: After looking at it a bit, would setting save to False on these two calls to update_pair fix the issue?
https://github.com/Nenotriple/img-txt_viewer/blob/665cfd6b3516ef5772b95b5e48f4cd4de86200d6/img-txt_viewer.pyw#L3727
https://github.com/Nenotriple/img-txt_viewer/blob/665cfd6b3516ef5772b95b5e48f4cd4de86200d6/img-txt_viewer.pyw#L3751

Added these changes to my PR for review.

**Comment by Nenotriple** [comment]
I'm sorry you had to deal with the app messing with your captions. It's something that should have been fixed earlier.

I seriously appreciate that you've looked into this yourself, your changes appear to have fixed the issue, and I've merged your pull request.

**Comment by UrzasLegacy** [comment]
No problem at all! Thank you for developing this, I'm happy to be able to contribute!
