### ISSUE TITLE
Is this an issue in settings_manager?

### ISSUE THREAD

**Issue by UrzasLegacy** [Nenotriple/img-txt_viewer#40]
Checking 'self' for attributes rather than 'self.parent'

https://github.com/Nenotriple/img-txt_viewer/blob/9042cbeddd346423d6375ed06d43400d27663c01/main/scripts/settings_manager.py#L134-L135
https://github.com/Nenotriple/img-txt_viewer/blob/9042cbeddd346423d6375ed06d43400d27663c01/main/scripts/settings_manager.py#L260-L266
https://github.com/Nenotriple/img-txt_viewer/blob/9042cbeddd346423d6375ed06d43400d27663c01/main/scripts/settings_manager.py#L268-L270

**Comment by Nenotriple** [comment]
Yes that was an oversight when moving this into its own class/script.

I also spotted the font and size settings weren't being set when reading the settings.

I pushed the needed changes to the dev branch. Thanks for noticing this!
